### ISSUE TITLE
Unable to deploy using Garden.io: 'error upgrading connection'

### ISSUE THREAD

**Issue by Tails** [jelastic-jps/kubernetes#22]
I have a Jelastic instance at MassiveGrid (trial still for now). I'm trying to install OpenFaas (as an example) using Garden.io. However, I'm having a strange issue where (a fresh) Kubernetes complains that a port cannot be forwarded. Is there a possibility that you could check out what goes wrong in the cluster? I do not have this problem on GAE. 

I confined the issue into this repository: https://github.com/Tails/jelastic-kubernetes-garden-openfaas

**Comment by dfateyev** [comment]
Most likely related to a known issue with Traefik ingress controller (it cannot handle a HTTP connection upgrade properly). Basically, there are two options:
- Using an alternative ingress controller: Nginx or HAProxy (requires K8S 1.15.5+ on Jelastic);
- Using an environment endpoint.

You can contact your hoster support for more assistance in this matter.
