### ISSUE TITLE
No letsencrypt addon available from the dashboard with version v1.16.6

### ISSUE THREAD

**Issue by zadigus** [jelastic-jps/kubernetes#27]
I've tried today to install following manifest

https://github.com/jelastic-jps/kubernetes/blob/v1.16.6/manifest.jps

Though it works, i.e. it can be installed (it was not the case last week), I see no let's encrypt addon when I click the addon button on the worker nodes:

![image](https://user-images.githubusercontent.com/8761254/76945014-3e0b4b00-6902-11ea-9f2a-aa019336a863.png)

Is that intended? Is the only possible way to install that addon through the manifest (which I haven't tried yet)?

**Comment by zadigus** [comment]
I've noticed the letsencrypt addon requires the extip feature:
```yaml
requiredFeatures: extip
```
Because the addon isn't displayed on my dashboard, I assume the extip is not installed automatically and maybe a precondition to see the addon is that the extip be installed beforehand. I've just tried to test that theory: I've attached an external IP, waited a few minutes and tried again to see if I get that addon in the dashboard. It also does not work. Any idea what I could be missing?

**Comment by dfateyev** [comment]
Let's Encrypt is not supported for any Kubernetes environment layer now, although it's in our roadmap and support will be added in one of the upcoming releases.
There are two alternative options for now:
1) Install Jelastic BL (balancer) and then add LE addon there, so you can get Let's Encrypt support for the default Kubernetes ingress out-of-box. This is the easiest recommended alternative;
2) Custom CP layer IP binding and "cert-manager" manual installation, along to custom ingress controller. This option is more complicated and requires a lof of settings. The functionality of public IP assignment with "cert-manager" + LE will be officially available in the next Jelastic Kubernetes release.
