### ISSUE TITLE
yaml deployment script seems supported in manifest but not in settings

### ISSUE THREAD

**Issue by zadigus** [jelastic-jps/kubernetes#53]
In your manifest, [here](https://github.com/jelastic-jps/kubernetes/blob/v1.25.4/manifest.jps#L387), you seem to accept a yaml script, however in your settings, you don't propose the option [here](https://github.com/jelastic-jps/kubernetes/blob/v1.25.4/configs/settings.yaml#L4).

**Comment by dfateyev** [comment]
It's a leftover from a feature that we used in the past. It didn't progress well.
We can remove [this snippet](https://github.com/jelastic-jps/kubernetes/blob/v1.25.4/manifest.jps#L387) from the manifest, but leave it as is.
